name: lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    permissions:
      contents: read
    uses: gechr/actions/.github/workflows/lint.yaml@24aa7833c41452ff05697bdf2dd48f023bcdf33b # v0.2.5
    with:
      language: go
