name: lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    permissions:
      contents: read
    uses: gechr/actions/.github/workflows/lint.yaml@b670f2c89a30f7ab050bcffbf2177459ca63520b # v0.2.8
    with:
      language: go
