name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    permissions:
      contents: read
    uses: gechr/actions/.github/workflows/test.yaml@854917523e0f0f5208e64c557bd645509944170b # v0.2.6
    with:
      language: go
      runs-on: '["ubuntu-latest","windows-latest"]'
