name: zizmor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  zizmor:
    permissions:
      contents: read
      actions: read
      security-events: write
    uses: gechr/actions/.github/workflows/zizmor.yaml@f86637c131004611b2346f2f3102ed291b13a412 # v0.2.9
