name: zizmor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  zizmor:
    permissions:
      contents: read
      actions: read
      security-events: write
    uses: gechr/actions/.github/workflows/zizmor.yaml@9b9d051d433bfeb57bf7f88c65c41ae3cb23e000 # v0.2.7
